name = "CaratheodoryPruning"
uuid = "ab320bfc-8242-4797-bfc4-9370c33880e7"
authors = ["Filip Belik"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
